# Generated by Django 5.2.3 on 2025-07-13 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=5)),
                ('onsite_time_start', models.DateTimeField(null=True, verbose_name='Onsite Time Start')),
                ('onsite_time_end', models.TimeField(null=True, verbose_name='Onsite Time End')),
            ],
            options={
                'ordering': ['block'],
            },
        ),
        migrations.CreateModel(
            name='OnsiteSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
                ('email', models.EmailField(default='sample@gmail.com', max_length=254)),
                ('name', models.CharField(default='Jose Rizal', max_length=128)),
                ('block', models.CharField(max_length=5)),
                ('course', models.CharField(default='AB AM', max_length=32)),
                ('school', models.CharField(default='SOM', max_length=32)),
                ('entry_pass', models.URLField(default='https://google.com/entry_pass')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='12345', max_length=64)),
                ('qr_code', models.URLField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blockinfo.onsiteschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockinfo.student')),
            ],
        ),
    ]
